import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MuiNextLink from '@components/MuiNextLink';
import HeaderInfo from '@components/HeaderInfo';
import AddGuestListForm from '@components/AddGuestbookForm';
// import Guestbook from 'web3-guestbook';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Legacy.xyz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Legacy.xyz 
        </h1>


        <p className={styles.description}> </p>

        {/* <Guestbook title="Welcome to demo guestbook" /> */}
        <div>
        <HeaderInfo/>
        <AddGuestListForm/>
        </div>
      </main>
    </div>
  )
}
