import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MuiNextLink from '@components/MuiNextLink';
import HeaderInfo from '@components/HeaderInfo';
import AddGuestListForm from '@components/AddGuestbookForm';
import Image from 'next/image'
import headerBackground from "../public/background.svg"

// import Guestbook from 'web3-guestbook';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Legacy.xyz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        curate your digital legacy.
        </h1>
        <p className={styles.description}>Enable supporters of your project to leave a digital signature once they’ve visited your website.  A new era of social proof, and discovery of content. </p>
        <button className={styles.installButton}>Install</button>

      <Image src={headerBackground}/>
        <div>
        <HeaderInfo/>
        <AddGuestListForm/>
        </div>
      </main>
    </div>
  )
}
