import Head from 'next/head';
import styles from '../styles/Home.module.css';
import SignLegacy from '@components/SignLegacy';
import SignersList from '@components/SignersList';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hey, {`I'm`} XYZ.
        </h1>
        <p className={styles.description}> </p>
        <div>
        <SignLegacy/>
        <SignersList/>
        </div>
      </main>
    </div>
  )
}
