import Head from 'next/head';
import styles from '../styles/Home.module.css';
import SignLegacy from '@components/SignLegacy';
import SignersList from '@components/SignersList';
import { Container, Stack, Typography } from '@mui/material';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{p:5}}>
        <Stack spacing={5} alignItems="center">
          <Typography variant="h1" sx={{textAlign: 'center', fontSize: 4}}>
            Hey, {`I'm`} Legacy XYZ.
          </Typography>
          <SignLegacy projectId={'legacyxyz'}/>
          <SignersList projectId={'legacyxyz'}/>
        </Stack>
      </Container>
    </div>
  )
}
